Introduce a usermode +R (block unauthed user messages)
UndernetIRC/ircu2 pull request #33
Opened 2023-12-29 15:24 UTC by jhoneycutt

If a client sets mode +R, unauthenticated clients will receive an error when trying to privmsg, cprivmsg, notice, cnotice, or invite them. The message will be something like:

:London.UK.Eu.UnderNet.org 477 charlie alice :You need to be identified to a
  registered account to contact this user -- you can obtain an account from
  http://cservice.undernet.org/live/

This is the same numeric used when unauthed users try to join a +r channel, matching InspIRCd.

2024-07-27 18:22 UTC, entrope requested changes

2024-07-27 18:22 UTC, entrope commented on include/client.h
> +#define ClearBurst(x)            ClrFlag(x, FLAG_BURST)
Could you revise this to not touch whitespace on lines that don't have text changes?

2024-07-27 18:22 UTC, entrope commented on ircd/s_user.c
> +
... although I think this whitespace cleanup is fine.

2024-07-27 18:22 UTC, entrope commented on ircd/s_user.c
> +    return IsBlockUnauthUsers(dest) && !IsAccount(source);
It's probably a little clearer and faster to write this whole function as (with line wrapping where appropriate):
```
return IsBlockUnauthUsers(dest) && !(IsAccount(source) || IsChannelService(source) || IsServer(source));
```

2026-07-19 14:21 UTC, jhoneycutt commented on include/client.h
> +#define ClearBurst(x)            ClrFlag(x, FLAG_BURST)
The new macro is longer than any of the older macros, so I added the whitespace to maintain alignment. I left this as-is, but I can change it if that's preferred.

2026-07-19 14:21 UTC, jhoneycutt commented on ircd/s_user.c
> +    return IsBlockUnauthUsers(dest) && !IsAccount(source);
Updated to this form.

2026-07-24 06:37 UTC, merged